spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1341622180}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

security:
  jwt:
    secret: demo-jwt-secret-key-for-spring-security-2026
    expiration-millis: 7200000
